# Generated by Django 5.1.2 on 2024-10-13 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NFLPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('forty_yard_dash', models.FloatField()),
                ('vertical_jump', models.FloatField()),
                ('broad_jump', models.FloatField()),
                ('bench', models.IntegerField()),
                ('weight', models.FloatField()),
                ('three_cone', models.FloatField()),
            ],
        ),
    ]
