# Generated by Django 5.1.2 on 2024-10-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nflplayer',
            name='bench',
            field=models.IntegerField(),
        ),
    ]
