# Generated by Django 5.1.2 on 2024-10-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_nflplayer_bench'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nflplayer',
            name='bench',
            field=models.FloatField(),
        ),
    ]
