# Generated by Django 5.1.3 on 2024-12-05 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=5)),
                ('school', models.CharField(max_length=50)),
                ('years_ncaa', models.JSONField(blank=True, null=True)),
                ('year_drafted', models.IntegerField(blank=True, null=True)),
                ('draft_round', models.IntegerField(blank=True, null=True)),
                ('draft_team', models.IntegerField(blank=True, null=True)),
                ('career_av', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
