# Generated by Django 5.1.4 on 2024-12-05 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NCAATeams",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_name", models.CharField(max_length=50)),
                ("conference", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="PassingLeaders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(blank=True, null=True)),
                ("team", models.CharField(max_length=50)),
                ("conference", models.CharField(max_length=50)),
                ("games", models.IntegerField(blank=True, null=True)),
                ("cmp", models.IntegerField(blank=True, null=True)),
                ("att", models.IntegerField(blank=True, null=True)),
                ("comp_pct", models.FloatField(blank=True, null=True)),
                ("yds", models.IntegerField(blank=True, null=True)),
                ("td", models.IntegerField(blank=True, null=True)),
                ("td_pct", models.FloatField(blank=True, null=True)),
                ("int", models.IntegerField(blank=True, null=True)),
                ("int_pct", models.FloatField(blank=True, null=True)),
                ("adj_yds", models.FloatField(blank=True, null=True)),
                ("adj_yds_att", models.FloatField(blank=True, null=True)),
                ("yds_carr", models.FloatField(blank=True, null=True)),
                ("yds_g", models.FloatField(blank=True, null=True)),
                ("ratings", models.FloatField(blank=True, null=True)),
                ("awards", models.JSONField(blank=True, null=True)),
                (
                    "playerid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="db.playerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="YearlyNCAATeamData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(blank=True, null=True)),
                ("AP_Finish", models.IntegerField(blank=True, null=True)),
                ("wins", models.IntegerField(blank=True, null=True)),
                ("losses", models.IntegerField(blank=True, null=True)),
                ("OSRS", models.FloatField(blank=True, null=True)),
                ("DSRS", models.FloatField(blank=True, null=True)),
                ("SRS", models.FloatField(blank=True, null=True)),
                ("PPG", models.FloatField(blank=True, null=True)),
                ("Opp_PPG", models.FloatField(blank=True, null=True)),
                ("PassYd_att", models.FloatField(blank=True, null=True)),
                ("opp_passyds_att", models.FloatField(blank=True, null=True)),
                ("rushyd_att", models.FloatField(blank=True, null=True)),
                ("opp_rushyd_att", models.FloatField(blank=True, null=True)),
                ("totyds_att", models.FloatField(blank=True, null=True)),
                ("opp_totyds_att", models.FloatField(blank=True, null=True)),
                (
                    "teamid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="db.ncaateams"
                    ),
                ),
            ],
        ),
    ]
