# Generated by Django 5.1.3 on 2024-12-05 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0002_ncaateams_passingleaders_yearlyncaateamdata"),
    ]

    operations = [
        migrations.RenameField(
            model_name="playerprofile",
            old_name="draft_team",
            new_name="draft_pick",
        ),
    ]
