# Generated by Django 5.1.3 on 2024-12-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_rename_draft_team_playerprofile_draft_pick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearlyncaateamdata',
            name='teamid',
            field=models.CharField(max_length=60),
        ),
    ]
