# Generated by Django 5.1.3 on 2024-12-06 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_alter_yearlyncaateamdata_teamid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yearlyncaateamdata',
            old_name='DSRS',
            new_name='SOS',
        ),
        migrations.RemoveField(
            model_name='yearlyncaateamdata',
            name='OSRS',
        ),
        migrations.RemoveField(
            model_name='yearlyncaateamdata',
            name='PassYd_att',
        ),
        migrations.RemoveField(
            model_name='yearlyncaateamdata',
            name='opp_passyds_att',
        ),
        migrations.RemoveField(
            model_name='yearlyncaateamdata',
            name='opp_rushyd_att',
        ),
        migrations.RemoveField(
            model_name='yearlyncaateamdata',
            name='opp_totyds_att',
        ),
        migrations.RemoveField(
            model_name='yearlyncaateamdata',
            name='rushyd_att',
        ),
        migrations.RemoveField(
            model_name='yearlyncaateamdata',
            name='totyds_att',
        ),
    ]
