# Generated by Django 5.1.3 on 2025-01-22 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_conferences_rename_yearlyncaateamdata_teamsuccess_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncaateams',
            name='conference_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='db.conferences'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ncaateams',
            name='conference_name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
