# Generated by Django 5.1.3 on 2025-01-22 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_ncaateams_conference_id_ncaateams_conference_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ncaateams',
            name='conference_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.conferences'),
        ),
        migrations.AlterField(
            model_name='ncaateams',
            name='conference_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
