# Generated by Django 5.1.3 on 2025-01-22 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_alter_ncaateams_conference_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ncaateams',
            name='conference_name',
        ),
    ]
