# Generated by Django 5.1.3 on 2025-01-23 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_remove_ncaateams_conference_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferences',
            name='abbreviation',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
