# Generated by Django 5.1.3 on 2025-01-23 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_conferences_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='rbstats',
            name='year',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recstats',
            name='year',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamratings',
            name='year',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
