# Generated by Django 5.1.3 on 2025-01-31 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_rbstats_year_recstats_year_teamratings_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(max_length=10)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('forty', models.FloatField(blank=True, null=True)),
                ('vertical', models.FloatField(blank=True, null=True)),
                ('bench', models.IntegerField(blank=True, null=True)),
                ('broadjump', models.FloatField(blank=True, null=True)),
                ('threecone', models.FloatField(blank=True, null=True)),
                ('shuttle', models.FloatField(blank=True, null=True)),
                ('playerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.playerprofile')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.ncaateams')),
            ],
        ),
    ]
