# Generated by Django 5.1.3 on 2025-01-31 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_combine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recstats',
            old_name='rec_td',
            new_name='rush_yds',
        ),
        migrations.RenameField(
            model_name='recstats',
            old_name='rec_yds',
            new_name='td',
        ),
        migrations.RenameField(
            model_name='recstats',
            old_name='rec_ypg',
            new_name='ypg',
        ),
    ]
