# Generated by Django 5.1.3 on 2025-01-31 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0014_rename_rec_td_recstats_rush_yds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='age_drafted',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='draft_av',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='nfl_team',
            field=models.CharField(default=None, max_length=50, null=True, blank=True),
            preserve_default=False,
        ),
    ]
