# Generated by Django 5.1.3 on 2025-01-31 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0015_playerprofile_age_drafted_playerprofile_draft_av_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='nfl_team',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
