# Generated by Django 5.1.3 on 2025-02-17 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0017_nflcbteam_nfldeteam_nfldtteam_nfllbteam_nflolteam_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nfllbteam',
            old_name='pass_yds_att',
            new_name='pass_yds_g',
        ),
    ]
