# Generated by Django 5.1.3 on 2025-02-17 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0018_rename_pass_yds_att_nfllbteam_pass_yds_g'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfllbteam',
            name='qbhits',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfllbteam',
            name='sack_yds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfllbteam',
            name='sacks',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
