# Generated by Django 5.1.3 on 2025-02-17 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0019_nfllbteam_qbhits_nfllbteam_sack_yds_nfllbteam_sacks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nflteteam',
            old_name='firstdowns',
            new_name='pass_firstdowns',
        ),
        migrations.RenameField(
            model_name='nflteteam',
            old_name='td',
            new_name='pass_td',
        ),
        migrations.RenameField(
            model_name='nflteteam',
            old_name='yds',
            new_name='pass_yds',
        ),
        migrations.AddField(
            model_name='nflteteam',
            name='rush_firstdowns',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflteteam',
            name='rush_td',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflteteam',
            name='rush_yds',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
