# Generated by Django 5.1.3 on 2025-02-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0020_rename_firstdowns_nflteteam_pass_firstdowns_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nfldeteam',
            old_name='missed_tkl_pct',
            new_name='missed_tkl',
        ),
        migrations.RenameField(
            model_name='nfldtteam',
            old_name='missed_tkl_pct',
            new_name='missed_tkl',
        ),
        migrations.AddField(
            model_name='nflcbteam',
            name='offseasoninvestment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfldeteam',
            name='offseasoninvestment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfldtteam',
            name='offseasoninvestment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfllbteam',
            name='offseasoninvestment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflolteam',
            name='offseasoninvestment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflqbteam',
            name='offseasoninvestment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflrbteam',
            name='offseasoninvestment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflsteam',
            name='offseasoninvestment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflteteam',
            name='offseasoninvestment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflwrteam',
            name='offseasoninvestment',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
