# Generated by Django 5.1.3 on 2025-02-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0021_rename_missed_tkl_pct_nfldeteam_missed_tkl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamNeeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=5)),
                ('year', models.IntegerField()),
                ('qb_sop', models.FloatField(blank=True, null=True)),
                ('rb_sop', models.FloatField(blank=True, null=True)),
                ('wr_sop', models.FloatField(blank=True, null=True)),
                ('te_sop', models.FloatField(blank=True, null=True)),
                ('ol_sop', models.FloatField(blank=True, null=True)),
                ('de_sop', models.FloatField(blank=True, null=True)),
                ('dt_sop', models.FloatField(blank=True, null=True)),
                ('lb_sop', models.FloatField(blank=True, null=True)),
                ('cb_sop', models.FloatField(blank=True, null=True)),
                ('s_sop', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
