# Generated by Django 5.1.3 on 2025-02-20 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0022_teamneeds'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='school_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='db.ncaateams'),
            preserve_default=False,
        ),
    ]
