# Generated by Django 5.1.3 on 2025-02-20 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0023_playerprofile_school_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='school_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.ncaateams'),
        ),
    ]
