# Generated by Django 5.1.3 on 2025-02-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0024_alter_playerprofile_school_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
