# Generated by Django 5.1.3 on 2025-02-20 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0025_playerprofile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerprofile',
            name='school_id',
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.ncaateams'),
        ),
    ]
