# Generated by Django 5.1.3 on 2025-02-20 20:29

from django.db import migrations, models
from db.models import NCAATeams


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0026_remove_playerprofile_school_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='school',
            field=models.ForeignKey(NCAATeams, on_delete=models.CASCADE, null=True),
        )

    ]
