# Generated by Django 5.1.3 on 2025-02-20 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0027_auto_20250220_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='schoolid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.ncaateams'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='school',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
