# Generated by Django 5.1.2 on 2024-12-03 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=10)),
                ('school', models.CharField(blank=True, max_length=100, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('years_ncaa', models.JSONField(default=list, help_text='Years the player played in NCAA')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DraftInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_av', models.FloatField(blank=True, null=True)),
                ('draft_round', models.IntegerField(blank=True, null=True)),
                ('draft_pick', models.IntegerField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_info', to='core.player')),
            ],
        ),
        migrations.CreateModel(
            name='TeamYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('sos', models.FloatField(help_text='Strength of Schedule')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='years', to='core.team')),
            ],
            options={
                'unique_together': {('team', 'year')},
            },
        ),
        migrations.CreateModel(
            name='RushingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('attempts', models.IntegerField(default=0)),
                ('yards', models.IntegerField(default=0)),
                ('yards_per_attempt', models.FloatField(default=0.0)),
                ('touchdowns', models.IntegerField(default=0)),
                ('yards_per_game', models.FloatField(default=0.0)),
                ('awards', models.TextField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rushing_stats', to='core.player')),
                ('team_year', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rushing_stats', to='core.teamyear')),
            ],
            options={
                'unique_together': {('player', 'team_year', 'year')},
            },
        ),
        migrations.CreateModel(
            name='ReceivingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('receptions', models.IntegerField(default=0)),
                ('yards', models.IntegerField(default=0)),
                ('yards_per_reception', models.FloatField(default=0.0)),
                ('touchdowns', models.IntegerField(default=0)),
                ('games_played', models.IntegerField(default=0)),
                ('yards_per_game', models.FloatField(default=0.0)),
                ('awards', models.TextField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiving_stats', to='core.player')),
                ('team_year', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receiving_stats', to='core.teamyear')),
            ],
            options={
                'unique_together': {('player', 'team_year', 'year')},
            },
        ),
        migrations.CreateModel(
            name='PassingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('completions', models.IntegerField(default=0)),
                ('attempts', models.IntegerField(default=0)),
                ('yards', models.IntegerField(default=0)),
                ('touchdowns', models.IntegerField(default=0)),
                ('interceptions', models.IntegerField(default=0)),
                ('completion_pct', models.FloatField(blank=True, help_text='Completion percentage', null=True)),
                ('yards_per_attempt', models.FloatField(blank=True, help_text='Yards per attempt', null=True)),
                ('rating', models.FloatField(blank=True, help_text='Passer rating', null=True)),
                ('interception_pct', models.FloatField(blank=True, help_text='IntPCT', null=True)),
                ('touchdown_pct', models.FloatField(blank=True, help_text='TDPCT', null=True)),
                ('awards', models.TextField(blank=True, help_text='awards', null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passing_stats', to='core.player')),
                ('team_year', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='passing_stats', to='core.teamyear')),
            ],
            options={
                'unique_together': {('player', 'team_year', 'year')},
            },
        ),
    ]
