# Generated by Django 5.1.2 on 2024-11-13 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("college", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=10)),
                (
                    "player_rating",
                    models.FloatField(
                        default=0.0, help_text="AI-generated rating (0-100)"
                    ),
                ),
                ("image_url", models.URLField(blank=True, null=True)),
                ("year", models.IntegerField(default=2025)),
            ],
            options={
                "ordering": ["-player_rating"],
            },
        ),
        migrations.CreateModel(
            name="PlayerDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("biography", models.TextField(blank=True)),
                (
                    "stats_json",
                    models.JSONField(
                        default=dict, help_text="Position-specific statistics"
                    ),
                ),
                (
                    "rankings_json",
                    models.JSONField(
                        default=dict, help_text="Various ranking information"
                    ),
                ),
                ("scheme_fit", models.TextField(blank=True)),
                ("best_performance", models.TextField(blank=True)),
                (
                    "player",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="api.player",
                    ),
                ),
            ],
        ),
    ]
