# Generated by Django 5.1.2 on 2024-11-13 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NFLTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("logo_url", models.URLField()),
                ("current_pick", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("college", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=10)),
                ("height", models.IntegerField(help_text="Height in inches")),
                ("weight", models.IntegerField(help_text="Weight in pounds")),
                ("biography", models.TextField()),
                ("player_image", models.URLField(blank=True, null=True)),
                (
                    "draft_rating",
                    models.FloatField(help_text="AI-generated draft rating"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="MockDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed", models.BooleanField(default=False)),
                ("grade", models.CharField(max_length=2, null=True)),
                (
                    "user_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.nflteam"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MockDraftPick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pick_number", models.IntegerField()),
                ("ai_analysis", models.TextField()),
                (
                    "mock_draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="picks",
                        to="api.mockdraft",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.nflteam"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.player"
                    ),
                ),
            ],
            options={
                "ordering": ["pick_number"],
            },
        ),
        migrations.CreateModel(
            name="DraftPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("predicted_round", models.IntegerField()),
                ("predicted_overall_pick", models.IntegerField()),
                ("confidence_score", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to="api.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CollegeStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("games_played", models.IntegerField()),
                (
                    "stats_json",
                    models.JSONField(
                        help_text="Position-specific statistics stored as JSON"
                    ),
                ),
                ("best_performance", models.TextField(blank=True, null=True)),
                ("scheme", models.TextField(blank=True, null=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="college_stats",
                        to="api.player",
                    ),
                ),
            ],
            options={
                "unique_together": {("player", "year")},
            },
        ),
    ]
