# Generated by Django 5.1.3 on 2024-12-01 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.RemoveField(
            model_name='team',
            name='city',
        ),
        migrations.AddField(
            model_name='player',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='school',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='years_ncaa',
            field=models.JSONField(default=list, help_text='Years the player played in NCAA'),
        ),
        migrations.AlterField(
            model_name='passingstats',
            name='attempts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passingstats',
            name='completions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passingstats',
            name='interceptions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passingstats',
            name='touchdowns',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passingstats',
            name='yards',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receivingstats',
            name='receptions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receivingstats',
            name='touchdowns',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receivingstats',
            name='yards',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rushingstats',
            name='attempts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rushingstats',
            name='touchdowns',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rushingstats',
            name='yards',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='DraftInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_round', models.CharField(blank=True, max_length=10, null=True)),
                ('draft_pick', models.IntegerField(blank=True, null=True)),
                ('draft_av', models.FloatField(blank=True, null=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draft_info', to='api.player')),
            ],
        ),
        migrations.CreateModel(
            name='TeamYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('sos', models.FloatField(help_text='Strength of Schedule')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='years', to='api.team')),
            ],
            options={
                'unique_together': {('team', 'year')},
            },
        ),
        migrations.AddField(
            model_name='passingstats',
            name='team_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='passing_stats', to='api.teamyear'),
        ),
        migrations.AddField(
            model_name='receivingstats',
            name='team_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receiving_stats', to='api.teamyear'),
        ),
        migrations.AddField(
            model_name='rushingstats',
            name='team_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rushing_stats', to='api.teamyear'),
        ),
        migrations.AlterUniqueTogether(
            name='passingstats',
            unique_together={('player', 'team_year', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='receivingstats',
            unique_together={('player', 'team_year', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='rushingstats',
            unique_together={('player', 'team_year', 'year')},
        ),
        migrations.RemoveField(
            model_name='passingstats',
            name='games_played',
        ),
        migrations.RemoveField(
            model_name='receivingstats',
            name='games_played',
        ),
        migrations.RemoveField(
            model_name='rushingstats',
            name='games_played',
        ),
    ]
