# Generated by Django 5.1.3 on 2024-12-01 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_player_team_remove_team_city_player_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passingstats',
            name='completion_pct',
            field=models.FloatField(blank=True, help_text='Completion percentage', null=True),
        ),
        migrations.AddField(
            model_name='passingstats',
            name='rating',
            field=models.FloatField(blank=True, help_text='Passer rating', null=True),
        ),
        migrations.AddField(
            model_name='passingstats',
            name='yards_per_attempt',
            field=models.FloatField(blank=True, help_text='Yards per attempt', null=True),
        ),
        migrations.AddField(
            model_name='receivingstats',
            name='awards',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receivingstats',
            name='games_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='receivingstats',
            name='yards_per_game',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='receivingstats',
            name='yards_per_reception',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='rushingstats',
            name='awards',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rushingstats',
            name='yards_per_attempt',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='rushingstats',
            name='yards_per_game',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='passingstats',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='passingstats',
            name='completions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='passingstats',
            name='interceptions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='passingstats',
            name='touchdowns',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='passingstats',
            name='yards',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='receivingstats',
            name='receptions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='receivingstats',
            name='touchdowns',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='receivingstats',
            name='yards',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rushingstats',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rushingstats',
            name='touchdowns',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rushingstats',
            name='yards',
            field=models.IntegerField(default=0),
        ),
    ]
