# Generated by Django 5.1.3 on 2024-12-02 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_passingstats_completion_pct_passingstats_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passingstats',
            name='awards',
            field=models.TextField(blank=True, help_text='awards', null=True),
        ),
        migrations.AddField(
            model_name='passingstats',
            name='interception_pct',
            field=models.FloatField(blank=True, help_text='IntPCT', null=True),
        ),
        migrations.AddField(
            model_name='passingstats',
            name='touchdown_pct',
            field=models.FloatField(blank=True, help_text='TDPCT', null=True),
        ),
    ]
