# Generated by Django 5.1.3 on 2024-12-02 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_passingstats_awards_passingstats_interception_pct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftinfo',
            name='draft_round',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='draftinfo',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_info', to='api.player'),
        ),
    ]
