# Generated by Django 5.1.2 on 2024-12-03 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_draftinfo_draft_round_alter_draftinfo_player'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DraftInfo',
        ),
    ]
