# Generated by Django 5.1.2 on 2024-12-04 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_draftinfo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='passingstats',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='passingstats',
            name='player',
        ),
        migrations.RemoveField(
            model_name='passingstats',
            name='team_year',
        ),
        migrations.RemoveField(
            model_name='receivingstats',
            name='player',
        ),
        migrations.RemoveField(
            model_name='rushingstats',
            name='player',
        ),
        migrations.AlterUniqueTogether(
            name='receivingstats',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='receivingstats',
            name='team_year',
        ),
        migrations.AlterUniqueTogether(
            name='rushingstats',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rushingstats',
            name='team_year',
        ),
        migrations.RemoveField(
            model_name='teamyear',
            name='team',
        ),
        migrations.AlterUniqueTogether(
            name='teamyear',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='DraftInfo',
        ),
        migrations.DeleteModel(
            name='PassingStats',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='ReceivingStats',
        ),
        migrations.DeleteModel(
            name='RushingStats',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='TeamYear',
        ),
    ]
